name: zoom_clone
description: Flutter clone for zoom meeting app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  connectivity_plus: ^2.3.7
  font_awesome_flutter: ^10.2.1
  fluttertoast: ^8.0.9
  nil: ^1.1.1
  get_storage: ^2.0.3
  cloud_firestore: ^3.5.0
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  jitsi_meet: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_app_name: ^0.1.1
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.9.2

  #TODO: run these commands
  #flutter pub run flutter_native_splash:create
  #flutter pub run flutter_launcher_icons:main
  #pub global activate rename #to activate rename package
  #pub global run rename --bundleId com.hady.dev.#appname here#
  #pub global run rename --appname "#appname here#"

flutter_app_name:
  name: "" #add the app name here

flutter_native_splash:
  color: "" #TODO: add your app splash light theme color like "#FEF6F4"
  image:   #TODO: add your app image on splash light theme image like assets/images/app_icon_light.png in png format
  color_dark: "" #TODO: add your app splash dark theme color like "#323031"
  image_dark: #TODO: add your app image on splash dark theme image like assets/images/app_icon_dark.png in png format
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "" #TODO: add your app icon here in png format

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
